module.exports = {
	SCREEN_WIDTH: undefined,
	SCREEN_HEIGHT: undefined,
	PLAYGROUND_WIDTH: 4096,
	PLAYGROUND_HEIGHT: 2048,
	MAP_BLOCK_WIDTH: 7, //位运算 移位

	CRUMB_MAX_NUM: 256,

	ENEMY_SNAKE: 9,

	PLAYER_INIT_LENGTH: 5,

	INTERVAL_PATH_POINT: 2, // 位运算移位
	INIT_SPEED: 8, // 位运算移位
	ROTATE_SPEED: 0.0025 * 180,
	GROW_SCORE_POINT: 10,
	NORMAL_AI_UPDATE_INTERVAL: 75
}